### ISSUE TITLE
libdark.so is yolo4 libdarknet.so

### ISSUE THREAD

**Issue by scjdff** [CaptainEven/MyNanoDet#2]
lib = CDLL("/users/duanyou/backup_c6/v3tiny_experiments/yolov4/darknet/build-release/libdark.so", RTLD_GLOBAL)
  File "/home/ubuntu/anaconda3/envs/nanodet/lib/python3.8/ctypes/__init__.py", line 381, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: /users/duanyou/backup_c6/v3tiny_experiments/yolov4/darknet/build-release/libdark.so: cannot open shared object file: No such file or directory
i try use yolo4 libdarknet.so but it also fail

**Comment by CaptainEven** [comment]
@Just comment relative code will be ok, it's not used here.
